data:
  destination_vocab_size: 184
  destination_vocab_target_size: 184
  source_vocab_size: 178
  vocab_path: model_files/base_model_v1/vocab.json
model:
  decoder_path: ./model_files/decoder.pt
  encoder_path: ./model_files/encoder.pt
