import re


# def clean_special_chars(text):
#     text = text.replace("_", " __under_score__ ")
#     text = text.replace(":", " __colon__ ")
#     text = text.replace(".", " __pointer__ ")
#     text = text.replace(",", " __coma__ ")
#     text = text.replace("[", " __sq_barc_open__ ")
#     text = text.replace(">", " __greater_than__ ")
#     text = text.replace("*", " __star__ ")
#     text = text.replace("=", " __equal__ ")
#     text = text.replace("%", " __percent__ ")
#     text = text.replace("]", " __sq_brac_close__ ")
#     text = text.replace("@", " __at__ ")
#     text = text.replace("#", " __hash__ ")
#     text = text.replace("{", " __flr_brac_open__ ")
#     text = text.replace("}", " __flr_brac_close__ ")
#     text = text.replace("$", " __doller__ ")
#     text = text.replace("~", " __tilda__ ")
#     text = text.replace("<", " __less_than__ ")
#     text = text.replace("^", " __cap__ ")
#     text = text.replace("!", " __exclamation__ ")
#     text = text.replace("&", " __and__ ")
#     text = text.replace("(", " __small_brac_open__ ")
#     text = text.replace(")", " __small_brac_close__ ")
#     text = text.replace("?", " __question_mark__ ")
#     text = text.replace("+", " __plus__ ")
#     text = text.replace("/", " __forward_slash__ ")
#     text = text.replace("\\", " __back_slask__ ")
#     text = text.replace("-", " __minus__ ")
#     text = text.replace("|", " __pipe__ ")
#     return text


def clean_special_chars(text):
    text = text.replace("_", " _ ")
    text = text.replace(":", " : ")
    text = text.replace(".", " . ")
    text = text.replace(",", " , ")
    text = text.replace("[", " [ ")
    text = text.replace(">", " > ")
    text = text.replace("*", " * ")
    text = text.replace("=", " = ")
    text = text.replace("%", " % ")
    text = text.replace("]", " ] ")
    text = text.replace("@", " @ ")
    text = text.replace("#", " # ")
    text = text.replace("{", " { ")
    text = text.replace("}", " } ")
    text = text.replace("$", " $ ")
    text = text.replace("~", " ~ ")
    text = text.replace("<", " < ")
    text = text.replace("^", " ^ ")
    text = text.replace("!", " ! ")
    text = text.replace("&", " & ")
    text = text.replace("(", " ( ")
    text = text.replace(")", " ) ")
    text = text.replace("?", " ? ")
    text = text.replace("+", " + ")
    text = text.replace("/", " / ")
    text = text.replace("\\", " \\ ")
    text = text.replace("-", " - ")
    text = text.replace("|", " | ")
    return text


def clean_telugu_chars(text):
    text = text.replace("రూపాయలు", " రూపాయలు")
    text = text.replace("₹", " రూపాయలు ")


    # text = text.replace(" ఔ ", "")
    # text = text.replace("  ొ ", "")
    # text = text.replace(" డ ", "")
    # text = text.replace(" ట ", "")
    # text = text.replace(" ః ", "")
    # text = text.replace(" భ ", "")
    # text = text.replace(" ణ ", "")
    # text = text.replace(" ఖ ", "")
    # text = text.replace(" ధ ", "")
    # text = text.replace(" ఱ ", "")
    # text = text.replace("  ౌ ", "")
    # text = text.replace(" ళ ", "")
    # text = text.replace(" ృ ", "")
    # text = text.replace(" ఠ ", "")
    # text = text.replace(" ఋ ", "")
    # text = text.replace(" ఌ ", "")
    # text = text.replace(" ట ", " ")
    # text = text.replace(" ప ", " ")
    # text = text.replace(" డ ", " ")
    # text = text.replace(" మ ", " ")
    # text = text.replace(" ా ", " ")
    # text = text.replace(" ర ", " ")
    # text = text.replace(" ఊ ", " ")
    # text = text.replace(" జ ", " ")
    # text = text.replace(" ో ", " ")
    # text = text.replace(" హ ", " ")
    # text = text.replace(" య ", " ")
    # text = text.replace(" స ", " ")
    # text = text.replace(" ఉ ", " ")
    # text = text.replace(" చ ", " ")
    # text = text.replace(" ం ", " ")
    # text = text.replace(" ణ ", " ")
    # text = text.replace(" ఒ ", " ")
    # text = text.replace(" ఈ ", " ")
    # text = text.replace(" ఏ ", " ")
    # text = text.replace(" ఆ ", " ")
    # text = text.replace(" వ ", " ")
    # text = text.replace(" ఓ ", " ")
    # text = text.replace(" ఎ ", " ")
    # text = text.replace(" ల ", " ")
    # text = text.replace(" న ", " ")
    # text = text.replace(" అ ", " ")
    # text = text.replace(" ఐ ", " ")
    # text = text.replace(" ూ ", " ")
    # text = text.replace(" త ", " ")
    # text = text.replace(" ఇ ", " ")
    # text = text.replace(" క ", " ")
    # text = text.replace(" శ ", " ")
    # text = text.replace(" ద ", " ")
    # text = text.replace(" బ ", " ")
    # text = text.replace(" ఘ ", " ")
    # text = text.replace(" ఁ ", " ")
    # text = text.replace(" ృ ", " ")
    # text = text.replace(" ధ ", " ")
    # text = text.replace(" ే ", " ")
    # text = text.replace(" భ ", " ")
    # text = text.replace(" ళ ", " ")
    # text = text.replace(" థ ", " ")
    # text = text.replace(" ౄ ", " ")
    # text = text.replace(" ఔ ", " ")
    # text = text.replace(" ః ", " ")
    # text = text.replace(" ఫ ", " ")
    # text = text.replace(" ె ", " ")
    # text = text.replace(" ై ", " ")
    # text = text.replace(" ి ", " ")
    # text = text.replace(" ఖ ", " ")
    # text = text.replace(" ్ ", " ")
    # text = text.replace(" ీ ", " ")
    # text = text.replace(" ష ", " ")
    # text = text.replace(" ు ", " ")
    # text = text.replace(" ొ ", " ")
    # text = text.replace(" क ", " ")
    # text = text.replace(" ౯ ", " ")
    # text = text.replace(" ఠ ", " ")
    # text = text.replace(" ఱ ", " ")
    # text = text.replace(" ఝ ", " ")
    # text = text.replace(" ౦ ", " ")
    # text = text.replace(" ఋ ", " ")
    # text = text.replace(" ౌ ", " ")
    # text = text.replace(" ఌ ", " ")
    # text = text.replace(" గ ", " ")
    # text = text.replace(" ఛ ", " ")
    # text = text.replace(" ఢ ", " ")
    # text = text.replace(" ౨ ", " ")

    return text
